/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	fastgsharecapsintumdev1 "github.com/KontonGu/FaST-GShare/pkg/apis/fastgshare.caps.in.tum.de/v1"
	versioned "github.com/KontonGu/FaST-GShare/pkg/client/clientset/versioned"
	internalinterfaces "github.com/KontonGu/FaST-GShare/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/KontonGu/FaST-GShare/pkg/client/listers/fastgshare.caps.in.tum.de/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// FaSTPodInformer provides access to a shared informer and lister for
// FaSTPods.
type FaSTPodInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.FaSTPodLister
}

type faSTPodInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewFaSTPodInformer constructs a new informer for FaSTPod type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFaSTPodInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredFaSTPodInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredFaSTPodInformer constructs a new informer for FaSTPod type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredFaSTPodInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FastgshareV1().FaSTPods(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FastgshareV1().FaSTPods(namespace).Watch(context.TODO(), options)
			},
		},
		&fastgsharecapsintumdev1.FaSTPod{},
		resyncPeriod,
		indexers,
	)
}

func (f *faSTPodInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredFaSTPodInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *faSTPodInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&fastgsharecapsintumdev1.FaSTPod{}, f.defaultInformer)
}

func (f *faSTPodInformer) Lister() v1.FaSTPodLister {
	return v1.NewFaSTPodLister(f.Informer().GetIndexer())
}
